export const PAGE_IDS = {
    TOP_GAINERS: -1,
    TOP_LOSERS: -2,
    DEBT_FREE_COMPANIES: 2,
    HOLDING_COMPANIES: 36,
    IT_COMPANIES: 47,
    PHARMACEUTICAL_COMPANIES: 69,
    PNNY_STOCKS_COMPANIES: 23,
    CHEMICAL_COMPANIES: 19
}