FROM node:14.17.0 as builder

COPY package.json  ./

RUN yarn install && mkdir /app && mv ./node_modules ./app

WORKDIR /app

COPY . .

RUN yarn build



FROM nginx:alpine

COPY ./nginx.conf /etc/nginx/nginx.conf

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
